// <auto-generated />
using System;
using Keepass.DBLib;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Keepass.DBLib.Migrations
{
    [DbContext(typeof(KeepassDbContext))]
    [Migration("20251216104351_00001")]
    partial class _00001
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("AppUserVault", b =>
                {
                    b.Property<Guid>("SharedUsersId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SharedVaultsId")
                        .HasColumnType("TEXT");

                    b.HasKey("SharedUsersId", "SharedVaultsId");

                    b.HasIndex("SharedVaultsId");

                    b.ToTable("AppUserVault");
                });

            modelBuilder.Entity("Keepass.DBLib.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntraId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("Keepass.DBLib.Vault", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AppUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId", "Name")
                        .IsUnique();

                    b.ToTable("Vaults");
                });

            modelBuilder.Entity("Keepass.DBLib.VaultEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VaultId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("VaultId");

                    b.ToTable("VaultEntries");
                });

            modelBuilder.Entity("AppUserVault", b =>
                {
                    b.HasOne("Keepass.DBLib.AppUser", null)
                        .WithMany()
                        .HasForeignKey("SharedUsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Keepass.DBLib.Vault", null)
                        .WithMany()
                        .HasForeignKey("SharedVaultsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Keepass.DBLib.Vault", b =>
                {
                    b.HasOne("Keepass.DBLib.AppUser", "Creator")
                        .WithMany("Vaults")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("Keepass.DBLib.VaultEntry", b =>
                {
                    b.HasOne("Keepass.DBLib.Vault", "Vault")
                        .WithMany("Entries")
                        .HasForeignKey("VaultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vault");
                });

            modelBuilder.Entity("Keepass.DBLib.AppUser", b =>
                {
                    b.Navigation("Vaults");
                });

            modelBuilder.Entity("Keepass.DBLib.Vault", b =>
                {
                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
